/* =========================================================
   ROMANO DIGITAL MENU
   Main Application
   Vanilla JavaScript
   Rv4.3
========================================================= */

"use strict";


/* =========================================================
   01. ROMANO STORAGE
========================================================= */

const ROMANO_STORAGE_KEYS = {

    restaurant:
        "romano_restaurant",

    categories:
        "romano_categories",

    products:
        "romano_products"

};


/* =========================================================
   02. STORAGE HELPERS
========================================================= */

/**
 * Read JSON data from localStorage.
 *
 * @param {string} key
 * @param {*} fallback
 * @returns {*}
 */

function getStoredData(key, fallback) {

    try {

        const stored =
            localStorage.getItem(key);


        if (!stored) {

            return fallback;

        }


        return JSON.parse(stored);

    } catch (error) {

        console.error(
            `ROMANO storage read error [${key}]`,
            error
        );


        return fallback;

    }

}


/**
 * Write JSON data to localStorage.
 *
 * @param {string} key
 * @param {*} value
 * @returns {boolean}
 */

function setStoredData(key, value) {

    try {

        localStorage.setItem(
            key,
            JSON.stringify(value)
        );


        return true;

    } catch (error) {

        console.error(
            `ROMANO storage write error [${key}]`,
            error
        );


        return false;

    }

}


/**
 * Allow only safe navigation URLs for administrator-provided links.
 */
function getSafeExternalUrl(value) {
    const raw = String(value || "").trim();
    if (!raw || raw === "#") return "";
    try {
        const url = new URL(raw, window.location.href);
        if (!["https:", "http:"].includes(url.protocol)) return "";
        return url.href;
    } catch (_) {
        return "";
    }
}


/**
 * Allow seed/local images and the compressed data URLs generated by the admin.
 */
function getSafeImageSource(value) {
    const raw = String(value || "").trim();
    if (!raw) return "";
    if (/^data:image\/(?:jpeg|jpg|png|webp);base64,/i.test(raw)) return raw;
    try {
        const url = new URL(raw, window.location.href);
        if (["https:", "http:"].includes(url.protocol)) return url.href;
        if (url.protocol === "file:") return raw;
        if (url.origin === window.location.origin && !/[\"'<>]/.test(raw)) return url.href;
    } catch (_) {
        if (/^(?:\.?\/?)[^\"'<>]+$/.test(raw)) return raw;
    }
    return "";
}


/* =========================================================
   03. APPLICATION DATA
========================================================= */

/*
 * data.js provides the default seed data.
 *
 * localStorage becomes the active data source after
 * the Admin Panel has saved changes.
 */

let restaurantConfig =
    getStoredData(
        ROMANO_STORAGE_KEYS.restaurant,
        structuredClone(restaurantData)
    );


let menuCategories =
    getStoredData(
        ROMANO_STORAGE_KEYS.categories,
        structuredClone(categories)
    );


let menuProducts =
    getStoredData(
        ROMANO_STORAGE_KEYS.products,
        structuredClone(products)
    );


/**
 * Normalize all application data.
 *
 * This protects the customer menu from old or incomplete
 * data that may have been created before the Admin Panel
 * was introduced.
 */

function normalizeApplicationData() {
    if (!restaurantConfig || typeof restaurantConfig !== "object" || Array.isArray(restaurantConfig)) {
        restaurantConfig = structuredClone(restaurantData);
    }

    if (!Array.isArray(menuCategories)) {
        menuCategories = structuredClone(categories);
    }

    if (!Array.isArray(menuProducts)) {
        menuProducts = structuredClone(products);
    }

    menuCategories = menuCategories
        .filter(category => category && typeof category === "object")
        .map(category => ({
            ...category,
            id: String(category.id || "").trim(),
            name: String(category.name || "").trim(),
            image: getSafeImageSource(category.image)
        }))
        .filter(category => category.id && category.name);

    menuProducts = menuProducts
        .filter(product => product && typeof product === "object")
        .map(product => ({
            ...product,
            id: String(product.id || "").trim(),
            name: String(product.name || "").trim(),
            category: String(product.category || "").trim(),
            price: Number.isFinite(Number(product.price)) && Number(product.price) > 0 ? Number(product.price) : 0,
            active: product.active !== false,
            featured: product.featured === true,
            badge: String(product.badge || "").trim(),
            rating: product.rating || "★★★★★",
            image: getSafeImageSource(product.image),
            description: String(product.description || "").trim(),
            categoryName: getCategoryName(product.category, product.categoryName),
            // Lets the language layer show the category in any language without a second lookup.
            categoryTranslations: menuCategories.find(item => item.id === String(product.category || "").trim())?.translations
        }))
        .filter(product => product.id && product.name && product.category);
}


/**
 * Return category name using the current category list.
 *
 * @param {string} categoryId
 * @param {string} fallback
 * @returns {string}
 */

function getCategoryName(
    categoryId,
    fallback = ""
) {

    const category =
        menuCategories.find(
            item =>
                item.id === categoryId
        );


    return (
        category?.name ||
        fallback ||
        ""
    );

}


/* Normalize data before rendering. */

normalizeApplicationData();


/* =========================================================
   04. DOM ELEMENTS
========================================================= */

let productModalPreviousFocus = null;

const DOM = {

    body:
        document.body,

    header:
        document.querySelector(".site-header"),

    brandName:
        document.querySelectorAll(".brand-name"),

    brandTagline:
        document.querySelectorAll(".brand-tagline"),

    menuToggle:
        document.querySelector(".menu-toggle"),

    mainNavigation:
        document.querySelector(".main-navigation"),

    navigationClose:
        document.querySelector(".navigation-close"),

    navigationList:
        document.querySelector(".navigation-list"),

    navigationCategoryList:
        document.querySelector(".navigation-category-list"),

    categoriesGrid:
        document.querySelector("#categories-grid"),

    featuredProducts:
        document.querySelector("#featured-products"),

    menuCategories:
        document.querySelector("#menu-categories"),

    restaurantAddress:
        document.querySelectorAll(
            "[data-restaurant-address]"
        ),

    restaurantPhone:
        document.querySelectorAll(
            "[data-restaurant-phone]"
        ),

    restaurantInstagram:
        document.querySelectorAll(
            "[data-restaurant-instagram]"
        ),

    productModal:
        document.querySelector(".product-modal"),

    modalBackdrop:
        document.querySelector(".modal-backdrop"),

    modalClose:
        document.querySelector(".modal-close"),

    modalImage:
        document.querySelector(
            "#modal-product-image"
        ),

    modalCategory:
        document.querySelector(
            ".modal-category"
        ),

    modalTitle:
        document.querySelector(
            ".modal-title"
        ),

    modalDescription:
        document.querySelector(
            ".modal-description"
        ),

    modalMeta:
        document.querySelector(
            "#modal-product-meta"
        )

};


/* =========================================================
   05. INITIALIZATION
========================================================= */

document.addEventListener(
    "DOMContentLoaded",
    initializeApplication
);


async function initializeApplication() {

    initializeSplashScreen();


    /*
     * Re-read localStorage at initialization time.
     *
     * This makes the application safer when the page is
     * opened after changes were made by the Admin Panel.
     */

    refreshApplicationData();

    // Production mode: the public API is the source of truth; local seed data remains the offline fallback.
    try {
        const language = window.ROMANO_I18N?.language || "fa";
        const remote = await window.RomanoPublicAPI?.load?.(document.body.dataset.restaurantSlug || "romano", language);
        if (remote?.restaurant) {
            restaurantConfig = { ...restaurantConfig, ...remote.restaurant, instagram: remote.restaurant.instagram || remote.restaurant.instagram_url || "" };
            if (Array.isArray(remote.categories) && remote.categories.length) menuCategories = remote.categories;
            if (Array.isArray(remote.products) && remote.products.length) menuProducts = remote.products;
            normalizeApplicationData();
        }
    } catch (error) {
        console.warn("ROMANO public API unavailable; using local offline data.", error);
    }

    renderRestaurantInformation();

    renderCategories();

    renderFeaturedProducts();

    renderMenuCategories();

    renderNavigation();

    enhanceHorizontalScrollers();

    initializeMenu();

    initializeModal();

    initializeImageFallbacks();

    initializeHeroMenuButton();

    initializeCategoryObserver();
    initializePrimaryNavigationObserver();

    document.addEventListener("romano:language-changed", () => {
        renderRestaurantInformation();
        renderCategories();
        renderFeaturedProducts();
        renderMenuCategories();
        renderNavigation();
        if (typeof window.renderSignatureDish === "function") window.renderSignatureDish();
        enhanceHorizontalScrollers();
        initializeCategoryObserver();
        initializePrimaryNavigationObserver();
        if (DOM.productModal?.classList.contains("is-open") && window.RomanoActiveProduct?.id) {
            openProductModal(window.RomanoActiveProduct.id);
        }
        window.dispatchEvent(new CustomEvent("romano:data-updated"));
    });

}


/**
 * Show the splash screen for at least a short, deliberate
 * moment (so it reads as a branded intro, not a flash), and
 * hide it once the window has fully loaded — fonts, the hero
 * background, and the logo included — whichever comes later.
 *
 * A safety timeout guarantees the splash never blocks the
 * site indefinitely if "load" is delayed for some reason
 * (slow connection, a stalled asset, etc.).
 */

function initializeSplashScreen() {

    const splash =
        document.querySelector("#splash-screen");


    if (!splash) {

        return;

    }


    const MINIMUM_VISIBLE_MS = 600;

    const MAXIMUM_WAIT_MS = 4000;

    const shownAt =
        performance.now();

    let hidden =
        false;


    function hideSplash() {

        if (hidden) {

            return;

        }


        hidden = true;


        const elapsed =
            performance.now() - shownAt;

        const remaining =
            Math.max(
                0,
                MINIMUM_VISIBLE_MS - elapsed
            );


        window.setTimeout(
            () => {

                splash.classList.add(
                    "is-hidden"
                );

                splash.setAttribute(
                    "aria-hidden",
                    "true"
                );


                /*
                 * Removed after the fade-out transition so
                 * it doesn't linger in the DOM or the
                 * accessibility tree.
                 */

                window.setTimeout(
                    () => splash.remove(),
                    650
                );

            },
            remaining
        );

    }


    if (document.readyState === "complete") {

        hideSplash();

    } else {

        window.addEventListener(
            "load",
            hideSplash,
            { once: true }
        );

    }


    window.setTimeout(
        hideSplash,
        MAXIMUM_WAIT_MS
    );

}


/* =========================================================
   06. DATA REFRESH
========================================================= */

/**
 * Reload current application data from localStorage.
 *
 * This is intentionally kept separate from initialization
 * so the application can refresh its data when necessary.
 */

function refreshApplicationData() {

    restaurantConfig =
        getStoredData(
            ROMANO_STORAGE_KEYS.restaurant,
            structuredClone(restaurantData)
        );


    menuCategories =
        getStoredData(
            ROMANO_STORAGE_KEYS.categories,
            structuredClone(categories)
        );


    menuProducts =
        getStoredData(
            ROMANO_STORAGE_KEYS.products,
            structuredClone(products)
        );


    normalizeApplicationData();

}


/* =========================================================
   07. RESTAURANT INFORMATION
========================================================= */

function renderRestaurantInformation() {

    const localizedRestaurant = window.ROMANO_I18N?.localizeRestaurant?.(restaurantConfig) || restaurantConfig;

    DOM.brandName.forEach(
        element => {

            element.textContent =
                (localizedRestaurant.name || restaurantConfig.name || "");

        }
    );


    DOM.brandTagline.forEach(
        element => {

            element.textContent =
                (localizedRestaurant.tagline || restaurantConfig.tagline || "");

        }
    );


    DOM.restaurantAddress.forEach(
        element => {

            element.textContent =
                (localizedRestaurant.address || restaurantConfig.address || "");

        }
    );


    DOM.restaurantPhone.forEach(
        element => {

            const phone =
                restaurantConfig.phone || "";


            element.textContent =
                phone;

            element.removeAttribute("href");

            if (phone) {
                element.href =
                    `tel:${phone.replace(/\s+/g, "")}`;
            }

        }
    );


    DOM.restaurantInstagram.forEach(
        element => {

            const instagram =
                getSafeExternalUrl(restaurantConfig.instagram);

            element.removeAttribute("href");
            element.removeAttribute("target");
            element.removeAttribute("rel");

            if (instagram) {
                element.href =
                    instagram;
                element.target =
                    "_blank";
                element.rel =
                    "noopener noreferrer";
            }

        }
    );

}


/* =========================================================
   08. CATEGORIES
========================================================= */

function renderCategories() {

    if (!DOM.categoriesGrid) {

        return;

    }


    DOM.categoriesGrid.innerHTML =
        "";


    const availableCategories = menuCategories.filter(category =>
        getProductsByCategory(category.id).length > 0
    );

    availableCategories.forEach((category, index) => {
        DOM.categoriesGrid.appendChild(createCategoryCard(category, index));
    });

}


/**
 * Create one category card.
 *
 * @param {Object} category
 * @param {number} index
 * @returns {HTMLElement}
 */

function createCategoryCard(
    category,
    index
) {

    category = window.ROMANO_I18N?.localizeCategory(category) || category;

    const article =
        document.createElement("article");


    article.className =
        "category-card";


    article.dataset.category =
        category.id;


    article.tabIndex =
        0;


    article.setAttribute(
        "role",
        "button"
    );


    article.setAttribute(
        "aria-label",
        window.ROMANO_I18N?.ui?.("categoryView", category.name) || `مشاهده ${category.name}`
    );


    article.innerHTML = `

        <div class="category-image">
            ${category.image
                ? `<img src="${escapeAttribute(category.image)}" alt="${escapeAttribute(category.name)}" loading="lazy">`
                : `<div class="image-fallback" aria-hidden="true">ROMANO</div>`}
        </div>


        <div class="category-overlay"></div>


        <div class="category-content">

            <span class="category-index">
                ${String(index + 1).padStart(2, "0")}
            </span>


            <h3 class="category-name">
                ${escapeHTML(category.name)}
            </h3>


            <span class="category-arrow">
                ←
            </span>

        </div>

    `;


    const activateCategory = () => {

        scrollToCategory(
            category.id
        );

    };


    article.addEventListener(
        "click",
        activateCategory
    );


    article.addEventListener(
        "keydown",
        event => {

            if (
                event.key === "Enter" ||
                event.key === " "
            ) {

                event.preventDefault();

                activateCategory();

            }

        }
    );


    return article;

}


/* =========================================================
   09. FEATURED PRODUCTS
========================================================= */

function renderFeaturedProducts() {

    if (!DOM.featuredProducts) {

        return;

    }


    DOM.featuredProducts.innerHTML =
        "";


    const featured =
        getFeaturedProducts();


    featured.forEach(
        product => {

            const card =
                createProductCard(
                    product
                );


            DOM.featuredProducts.appendChild(
                card
            );

        }
    );


    /*
     * If no active featured product exists,
     * hide the section instead of leaving an empty block.
     */

    const section =
        DOM.featuredProducts.closest(
            "section"
        );


    if (section) {

        section.hidden =
            featured.length === 0;

    }

}


/* =========================================================
   10. MENU CATEGORIES
========================================================= */

function renderMenuCategories() {

    if (!DOM.menuCategories) {

        return;

    }


    DOM.menuCategories.innerHTML =
        "";


    menuCategories.forEach(
        (category, index) => {

            const categoryProducts =
                getProductsByCategory(
                    category.id
                );


            /*
             * Do not display empty categories.
             */

            if (
                categoryProducts.length === 0
            ) {

                return;

            }


            const section =
                createMenuCategory(
                    category,
                    categoryProducts,
                    index
                );


            DOM.menuCategories.appendChild(
                section
            );

        }
    );

}


/**
 * Create complete category section.
 *
 * @param {Object} category
 * @param {Array} categoryProducts
 * @param {number} index
 * @returns {HTMLElement}
 */

function createMenuCategory(
    category,
    categoryProducts,
    index
) {

    category = window.ROMANO_I18N?.localizeCategory(category) || category;
    categoryProducts = categoryProducts.map(product => window.ROMANO_I18N?.localizeProduct(product) || product);

    const section =
        document.createElement("section");


    section.className =
        "menu-category";


    section.id =
        `category-${category.id}`;


    section.innerHTML = `

        <div class="menu-category-header">

            <div class="menu-category-heading">

                <span class="menu-category-index">
                    ${String(index + 1).padStart(2, "0")}
                </span>

                <h2 class="menu-category-title">
                    ${escapeHTML(category.name)}
                </h2>

            </div>


            <span class="menu-category-count">
                ${window.ROMANO_I18N?.ui?.("menuCount", categoryProducts.length) || `${categoryProducts.length} انتخاب`}
            </span>

        </div>


        <div class="menu-category-products"></div>

    `;


    const productsContainer =
        section.querySelector(
            ".menu-category-products"
        );


    categoryProducts.forEach(
        product => {

            productsContainer.appendChild(
                createProductCard(product)
            );

        }
    );


    return section;

}



/* =========================================================
   10b. RATING STARS + HORIZONTAL SCROLL UX
========================================================= */

/**
 * Parse rating string/number into 0–5 integer.
 * @param {string|number} rating
 * @returns {number}
 */
function parseRatingValue(rating) {

    if (typeof rating === "number") {

        return Math.min(
            5,
            Math.max(
                0,
                Math.round(rating)
            )
        );

    }


    const text =
        String(
            rating || ""
        );


    const stars =
        text.match(
            /★/g
        );


    if (stars) {

        return Math.min(
            5,
            stars.length
        );

    }


    const numeric =
        parseFloat(
            text
        );


    if (
        Number.isFinite(
            numeric
        )
    ) {

        return Math.min(
            5,
            Math.max(
                0,
                Math.round(
                    numeric
                )
            )
        );

    }


    return 5;

}


/**
 * Render editorial SVG star row.
 * @param {string|number} rating
 * @returns {string}
 */
function renderRatingStars(rating) {

    const value =
        parseRatingValue(
            rating
        );


    const parts = [
        `<span class="product-rating" role="img" aria-label="${escapeAttribute(window.ROMANO_I18N?.ui?.("rating", value) || `امتیاز ${value} از ۵`)}">`
    ];


    for (
        let index = 1;
        index <= 5;
        index += 1
    ) {

        const filled =
            index <= value
                ? " is-filled"
                : "";


        parts.push(
            `<svg class="product-star${filled}" viewBox="0 0 24 24" width="12" height="12" aria-hidden="true" focusable="false"><path d="M12 3.2l2.4 5.1 5.6.6-4.2 3.8 1.2 5.5L12 15.6 6.9 18.2l1.2-5.5L4 8.9l5.6-.6L12 3.2z"/></svg>`
        );

    }


    parts.push(
        "</span>"
    );


    return parts.join(
        ""
    );

}


/**
 * Wrap horizontal product rows with prev/next controls.
 */
function enhanceHorizontalScrollers() {

    const scrollers =
        document.querySelectorAll(
            ".products-grid-horizontal, .menu-category-products"
        );


    scrollers.forEach(
        scroller => {

            if (
                scroller.closest(
                    ".products-scroll-shell"
                )
            ) {

                return;

            }


            const shell =
                document.createElement(
                    "div"
                );


            shell.className =
                "products-scroll-shell";


            scroller.parentNode.insertBefore(
                shell,
                scroller
            );


            shell.appendChild(
                scroller
            );


            const prev =
                document.createElement(
                    "button"
                );


            prev.type =
                "button";

            prev.className =
                "products-scroll-btn products-scroll-btn--prev";

            prev.setAttribute(
                "aria-label",
                window.ROMANO_I18N?.ui?.("previous") || "مشاهده موارد قبلی"
            );

            prev.innerHTML =
                `<svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"><path d="M9 6l6 6-6 6" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`;


            const next =
                document.createElement(
                    "button"
                );


            next.type =
                "button";

            next.className =
                "products-scroll-btn products-scroll-btn--next";

            next.setAttribute(
                "aria-label",
                window.ROMANO_I18N?.ui?.("next") || "مشاهده موارد بعدی"
            );

            next.innerHTML =
                `<svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"><path d="M15 6l-6 6 6 6" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`;


            shell.appendChild(
                prev
            );

            shell.appendChild(
                next
            );


            const updateButtons =
                () => {

                    const maxScroll = Math.max(0, scroller.scrollWidth - scroller.clientWidth);
                    const direction = getComputedStyle(scroller).direction;
                    const raw = scroller.scrollLeft;
                    const normalized = direction === "rtl"
                        ? (raw < 0 ? Math.abs(raw) : Math.max(0, maxScroll - raw))
                        : Math.max(0, raw);

                    prev.hidden = maxScroll < 8 || normalized < 8;
                    next.hidden = maxScroll < 8 || normalized > maxScroll - 8;

                };


            const scrollByDir =
                direction => {

                    const amount =
                        Math.max(
                            240,
                            Math.floor(
                                scroller.clientWidth * 0.72
                            )
                        );


                    scroller.scrollBy(
                        {
                            left:
                                direction * amount * (
                                    document.documentElement.dir === "rtl"
                                        ? -1
                                        : 1
                                ),
                            behavior:
                                "smooth"
                        }
                    );

                };


            prev.addEventListener(
                "click",
                () => scrollByDir(
                    -1
                )
            );


            next.addEventListener(
                "click",
                () => scrollByDir(
                    1
                )
            );


            scroller.addEventListener(
                "scroll",
                updateButtons,
                {
                    passive:
                        true
                }
            );


            window.addEventListener(
                "resize",
                updateButtons
            );


            requestAnimationFrame(
                updateButtons
            );

        }
    );

}


/* =========================================================
   11. PRODUCT CARD
========================================================= */

function createProductCard(product) {

    product = window.ROMANO_I18N?.localizeProduct(product) || product;

    const article =
        document.createElement("article");


    article.className =
        "product-card";


    article.dataset.productId =
        product.id;


    const badge =
        product.badge
            ? `
                <span class="product-badge">
                    ${escapeHTML(product.badge)}
                </span>
              `
            : "";


    const price =
        product.price > 0
            ? `
                <span class="product-price">
                    ${formatPrice(product.price)}
                </span>
              `
            : "";


    article.innerHTML = `

        <div class="product-image-wrapper">
            ${product.image
                ? `<img src="${escapeAttribute(product.image)}" alt="${escapeAttribute(product.name)}" loading="lazy">`
                : `<div class="image-fallback" aria-hidden="true">ROMANO</div>`}
            ${badge}
        </div>


        <div class="product-body">

            <div class="product-topline">

                <span class="product-category">
                    ${escapeHTML(product.categoryName)}
                </span>

                ${renderRatingStars(product.rating)}

            </div>


            <h3 class="product-name">
                ${escapeHTML(product.name)}
            </h3>


            <p class="product-description">
                ${escapeHTML(product.description)}
            </p>


            ${price}

        </div>


        <button
            class="product-card-button"
            type="button"
            aria-label="${escapeAttribute(window.ROMANO_I18N?.ui?.("productView", product.name) || `مشاهده ${product.name}`)}"
        ></button>

    `;


    const button =
        article.querySelector(
            ".product-card-button"
        );


    button.addEventListener(
        "click",
        event => {

            event.preventDefault();


            openProductModal(
                product.id
            );

        }
    );


    return article;

}


/* =========================================================
   12. BODY SCROLL LOCK
========================================================= */

/*
 * Both the product modal and the hamburger navigation lock
 * page scroll by adding "modal-open" to <body>. Two
 * independent overlays share one class, so the lock must be
 * derived from BOTH states every time either one changes —
 * otherwise closing one overlay can unlock scroll while the
 * other overlay is still open.
 */

function syncBodyScrollLock() {

    const navigationOpen =
        DOM.mainNavigation?.classList.contains(
            "is-open"
        ) ?? false;


    const modalOpen =
        DOM.productModal?.classList.contains(
            "is-open"
        ) ?? false;


    DOM.body.classList.toggle(
        "modal-open",
        navigationOpen || modalOpen
    );

}


/* =========================================================
   13. PRODUCT MODAL
========================================================= */

function initializeModal() {
    if (!DOM.productModal) return;

    DOM.productModal.addEventListener("click", event => {
        if (event.target.closest("[data-modal-close]")) closeProductModal();
    });

    document.addEventListener("keydown", event => {
        if (!DOM.productModal.classList.contains("is-open")) return;

        if (event.key === "Escape") {
            event.preventDefault();
            closeProductModal();
            return;
        }

        if (event.key !== "Tab") return;

        const focusables = Array.from(DOM.productModal.querySelectorAll(
            'button:not([disabled]), a[href], input:not([disabled]), textarea:not([disabled]), select:not([disabled]), [tabindex]:not([tabindex="-1"])'
        )).filter(element => element.offsetParent !== null);

        if (!focusables.length) {
            event.preventDefault();
            DOM.modalClose?.focus();
            return;
        }

        const first = focusables[0];
        const last = focusables[focusables.length - 1];
        if (event.shiftKey && document.activeElement === first) {
            event.preventDefault();
            last.focus();
        } else if (!event.shiftKey && document.activeElement === last) {
            event.preventDefault();
            first.focus();
        }
    });
}


/**
 * Open product modal.
 *
 * @param {string} productId
 */

function openProductModal(productId) {

    const rawProduct =
        getProductById(
            productId
        );

    const product =
        rawProduct
            ? (window.ROMANO_I18N?.localizeProduct?.(rawProduct) || rawProduct)
            : rawProduct;


    if (
        !product ||
        !DOM.productModal
    ) {

        return;

    }

    if (!DOM.productModal.classList.contains("is-open")) {
        productModalPreviousFocus =
            document.activeElement instanceof HTMLElement
                ? document.activeElement
                : null;
    }

    // Public UI state for progressive enhancements (share/deep-link).
    // The core modal remains the single owner of product selection.
    window.RomanoActiveProduct = product;

    if (DOM.modalImage) {
        const imageWrapper = DOM.modalImage.closest(".modal-image-wrapper");
        DOM.modalImage.dataset.fallbackApplied = "";
        DOM.modalImage.style.display = "";

        imageWrapper?.querySelectorAll(".image-fallback").forEach(node => node.remove());

        const safeImage = getSafeImageSource(product.image);
        if (safeImage) {
            DOM.modalImage.src = safeImage;
            DOM.modalImage.alt = product.name || "";
            if (imageWrapper) imageWrapper.hidden = false;
        } else {
            DOM.modalImage.removeAttribute("src");
            DOM.modalImage.alt = "";
            if (imageWrapper) {
                imageWrapper.hidden = false;
                const fallback = document.createElement("div");
                fallback.className = "image-fallback";
                fallback.setAttribute("aria-hidden", "true");
                fallback.textContent = "ROMANO";
                imageWrapper.appendChild(fallback);
            }
        }
    }


    if (DOM.modalCategory) {

        DOM.modalCategory.textContent =
            product.categoryName || "";

    }


    if (DOM.modalTitle) {

        DOM.modalTitle.textContent =
            product.name || "";

    }


    if (DOM.modalDescription) {

        DOM.modalDescription.textContent =
            product.description || "";

    }


    if (DOM.modalMeta) {

        const metaParts = [];


        if (product.rating) {

            metaParts.push(
                window.ROMANO_I18N?.ui?.("rating", parseRatingValue(product.rating)) || ("امتیاز " + parseRatingValue(product.rating) + " از ۵")
            );

        }


        if (product.price > 0) {

            metaParts.push(
                formatPrice(product.price)
            );

        }


        DOM.modalMeta.textContent =
            metaParts.join("  ·  ");

    }


    DOM.productModal.classList.add(
        "is-open"
    );


    DOM.productModal.setAttribute(
        "aria-hidden",
        "false"
    );

    requestAnimationFrame(() => DOM.modalClose?.focus());

    syncBodyScrollLock();

}


/**
 * Close product modal.
 */

function closeProductModal() {
    if (!DOM.productModal) return;

    DOM.productModal.classList.remove("is-open");
    DOM.productModal.setAttribute("aria-hidden", "true");
    syncBodyScrollLock();

    const target = productModalPreviousFocus;
    productModalPreviousFocus = null;
    window.RomanoActiveProduct = null;

    requestAnimationFrame(() => {
        if (target && document.contains(target)) target.focus();
    });
}


/* =========================================================
   14. CATEGORY NAVIGATION
========================================================= */

function scrollToCategory(categoryId) {

    const section =
        document.querySelector(
            `#category-${CSS.escape(categoryId)}`
        );


    if (!section) {

        return;

    }


    closeNavigation();


    section.scrollIntoView({
        behavior: "smooth",
        block: "start"
    });

}


/* =========================================================
   15. HAMBURGER MENU
========================================================= */

function initializeMenu() {

    if (!DOM.menuToggle || !DOM.mainNavigation) {
        return;
    }

    const panel =
        DOM.mainNavigation.querySelector(".navigation-inner");

    let previousFocus = null;

    DOM.menuToggle.addEventListener(
        "click",
        toggleNavigation
    );

    DOM.navigationClose?.addEventListener(
        "click",
        closeNavigation
    );

    DOM.mainNavigation.addEventListener(
        "click",
        event => {
            if (event.target === DOM.mainNavigation) {
                closeNavigation();
                return;
            }

            const link =
                event.target.closest("a[href]");

            if (!link || !DOM.mainNavigation.contains(link)) {
                return;
            }

            closeNavigation();
        }
    );

    document.addEventListener(
        "keydown",
        event => {
            if (!DOM.mainNavigation?.classList.contains("is-open")) {
                return;
            }

            if (event.key === "Escape") {
                event.preventDefault();
                closeNavigation();
                return;
            }

            if (event.key !== "Tab" || !panel) {
                return;
            }

            const focusables = Array.from(
                panel.querySelectorAll(
                    'a[href], button:not([disabled]), [tabindex]:not([tabindex="-1"])'
                )
            ).filter(
                element =>
                    element.offsetParent !== null &&
                    !element.hasAttribute("aria-hidden")
            );

            if (!focusables.length) {
                return;
            }

            const first = focusables[0];
            const last = focusables[focusables.length - 1];

            if (event.shiftKey && document.activeElement === first) {
                event.preventDefault();
                last.focus();
            } else if (!event.shiftKey && document.activeElement === last) {
                event.preventDefault();
                first.focus();
            }
        }
    );

    DOM.navigationClose?.addEventListener(
        "keydown",
        event => {
            if (event.key === "Enter" || event.key === " ") {
                event.preventDefault();
                closeNavigation();
            }
        }
    );

    // Keep the menu CTA as a shortcut to the full menu, without adding
    // another top-level route to the hamburger list.
    document
        .querySelector("[data-navigation-menu-cta]")
        ?.addEventListener(
            "click",
            () => {
                closeNavigation();
                document
                    .querySelector("#menu")
                    ?.scrollIntoView({
                        behavior: "smooth",
                        block: "start"
                    });
            }
        );

    // Used by open/closeNavigation for focus restoration.
    DOM.mainNavigation.__romanoFocus = {
        get previous() {
            return previousFocus;
        },
        set previous(value) {
            previousFocus = value;
        }
    };
}


/**
 * Toggle navigation.
 */

function toggleNavigation() {

    if (!DOM.mainNavigation) {
        return;
    }

    const isOpen =
        DOM.mainNavigation.classList.contains("is-open");

    if (isOpen) {
        closeNavigation();
    } else {
        openNavigation();
    }
}


/**
 * Open navigation.
 */

function openNavigation() {

    if (!DOM.mainNavigation) {

        return;

    }

    const panel =
        DOM.mainNavigation.querySelector(".navigation-inner");

    if (DOM.mainNavigation.__romanoFocus) {
        DOM.mainNavigation.__romanoFocus.previous =
            document.activeElement instanceof HTMLElement
                ? document.activeElement
                : DOM.menuToggle;
    }

    DOM.mainNavigation.classList.add(
        "is-open"
    );


    DOM.menuToggle?.classList.add(
        "is-active"
    );


    DOM.mainNavigation.setAttribute(
        "aria-hidden",
        "false"
    );


    DOM.menuToggle?.setAttribute(
        "aria-expanded",
        "true"
    );

    DOM.menuToggle?.setAttribute(
        "aria-label",
        "بستن منوی اصلی"
    );

    syncBodyScrollLock();

    // The drawer animates its visibility; wait until it is interactable
    // before moving focus so the browser does not reject focus on a
    // still-hidden descendant during the transition.
    window.setTimeout(() => {
        if (!DOM.mainNavigation?.classList.contains("is-open")) {
            return;
        }

        const firstFocusable =
            panel?.querySelector(
                'a[href], button:not([disabled]), [tabindex]:not([tabindex="-1"])'
            );

        firstFocusable?.focus();
    }, 360);

}


/**
 * Close navigation.
 */

function closeNavigation() {

    if (!DOM.mainNavigation) {

        return;

    }

    const previousFocus =
        DOM.mainNavigation.__romanoFocus?.previous;

    if (DOM.mainNavigation.__romanoFocus) {
        DOM.mainNavigation.__romanoFocus.previous = null;
    }

    DOM.mainNavigation.classList.remove(
        "is-open"
    );


    DOM.menuToggle?.classList.remove(
        "is-active"
    );


    DOM.mainNavigation.setAttribute(
        "aria-hidden",
        "true"
    );


    DOM.menuToggle?.setAttribute(
        "aria-expanded",
        "false"
    );

    DOM.menuToggle?.setAttribute(
        "aria-label",
        "باز کردن منوی اصلی"
    );

    syncBodyScrollLock();

    requestAnimationFrame(() => {
        previousFocus?.focus?.();
    });

}


/* =========================================================
   16. NAVIGATION LINKS
========================================================= */

function renderNavigation() {

    const categoryList = DOM.navigationCategoryList || document.querySelector(".navigation-category-list");

    if (!categoryList) {
        return;
    }

    // The primary navigation is intentionally static. Only category links
    // are data-driven so the drawer cannot accumulate duplicate core routes.
    categoryList.innerHTML = "";

    const availableCategories =
        menuCategories.filter(
            category =>
                getProductsByCategory(category.id).length > 0
        );

    availableCategories.map(category => window.ROMANO_I18N?.localizeCategory?.(category) || category).forEach(category => {
        const item = document.createElement("li");
        item.dataset.categoryLink = "true";
        item.innerHTML = `
            <a href="#category-${escapeAttribute(category.id)}" data-category-link="true">
                ${escapeHTML(category.name)}
            </a>
        `;
        categoryList.appendChild(item);
    });
}


/* =========================================================
   17. IMAGE FALLBACK
========================================================= */

function initializeImageFallbacks() {

    document.addEventListener(
        "error",
        event => {

            const element =
                event.target;


            if (
                element.tagName !== "IMG"
            ) {

                return;

            }


            handleImageError(
                element
            );

        },
        true
    );

}


/**
 * Replace broken image with a visual fallback.
 *
 * @param {HTMLImageElement} image
 */

function handleImageError(image) {

    if (
        image.dataset.fallbackApplied ===
        "true"
    ) {

        return;

    }


    image.dataset.fallbackApplied =
        "true";


    const wrapper =
        image.parentElement;


    if (!wrapper) {

        return;

    }


    const fallback =
        document.createElement("div");


    fallback.className =
        "image-fallback";


    fallback.textContent =
        "ROMANO";


    image.style.display =
        "none";


    wrapper.appendChild(
        fallback
    );

}


/* =========================================================
   18. HERO MENU BUTTON
========================================================= */

function initializeHeroMenuButton() {

    const heroMenuButton =
        document.querySelector(
            ".hero-button"
        );


    if (!heroMenuButton) {

        return;

    }


    heroMenuButton.addEventListener(
        "click",
        event => {

            event.preventDefault();


            const menuSection = document.querySelector("#menu");


            if (!menuSection) {

                return;

            }


            menuSection.scrollIntoView({
                behavior: "smooth",
                block: "start"
            });

        }
    );

}


/* =========================================================
   19. ACTIVE CATEGORY OBSERVER
========================================================= */

let categoryObserver = null;
let primaryNavigationObserver = null;

function initializeCategoryObserver() {

    categoryObserver?.disconnect();
    categoryObserver = null;

    const sections =
        document.querySelectorAll(
            ".menu-category"
        );


    if (
        sections.length === 0 ||
        !("IntersectionObserver" in window)
    ) {

        return;

    }


    categoryObserver =
        new IntersectionObserver(
            entries => {

                entries.forEach(
                    entry => {

                        if (
                            !entry.isIntersecting
                        ) {

                            return;

                        }


                        const categoryId =
                            entry.target.id.replace(
                                "category-",
                                ""
                            );


                        updateActiveNavigation(
                            categoryId
                        );

                    }
                );

            },
            {
                threshold: 0.35
            }
        );


    sections.forEach(section => categoryObserver.observe(section));

}


/**
 * Update active navigation item.
 *
 * @param {string} categoryId
 */

function updateActiveNavigation(
    sectionId
) {

    const links =
        document.querySelectorAll(
            ".navigation-list a, .navigation-category-list a"
        );

    if (!links.length) {
        return;
    }

    const isCategory =
        String(sectionId).startsWith("category-");

    links.forEach(link => {
        const href = link.getAttribute("href") || "";
        const isCategoryLink =
            link.closest(".navigation-category-list") !== null;

        if (isCategoryLink) {
            if (isCategory) {
                link.classList.toggle(
                    "is-active",
                    href === `#${sectionId}`
                );
            }
            return;
        }

        const matchesPrimary =
            href === `#${isCategory ? "menu" : sectionId}`;

        link.classList.toggle(
            "is-active",
            matchesPrimary
        );
    });
}


/* =========================================================
   20. PRIMARY NAVIGATION OBSERVER
========================================================= */

function initializePrimaryNavigationObserver() {
    primaryNavigationObserver?.disconnect();
    primaryNavigationObserver = null;

    if (!("IntersectionObserver" in window)) {
        return;
    }

    const sections =
        document.querySelectorAll(
            "#home, #featured, #menu, #story, #contact"
        );

    if (!sections.length) {
        return;
    }

    primaryNavigationObserver =
        new IntersectionObserver(
            entries => {
                entries.forEach(entry => {
                    if (!entry.isIntersecting) {
                        return;
                    }

                    updateActiveNavigation(entry.target.id);
                });
            },
            {
                rootMargin: "-30% 0px -55% 0px",
                threshold: 0.01
            }
        );

    sections.forEach(section => primaryNavigationObserver.observe(section));
}


/* =========================================================
   20. PRODUCT HELPERS
========================================================= */

/**
 * Return active products belonging to a category.
 *
 * @param {string} categoryId
 * @returns {Array}
 */

function getProductsByCategory(categoryId) {

    return menuProducts.filter(
        product =>
            product.category === categoryId &&
            product.active !== false
    );

}


/**
 * Return active featured products.
 *
 * @returns {Array}
 */

function getFeaturedProducts() {

    return menuProducts.filter(
        product =>
            product.featured === true &&
            product.active !== false
    );

}


/**
 * Find an active product by ID.
 *
 * @param {string} productId
 * @returns {Object|undefined}
 */

function getProductById(productId) {

    return menuProducts.find(
        product =>
            product.id === productId &&
            product.active !== false
    );

}


/* =========================================================
   21. FORMATTING HELPERS
========================================================= */

/**
 * Format product price.
 *
 * @param {number} price
 * @returns {string}
 */

function formatPrice(price) {

    const numericPrice =
        Number(price);


    if (
        !Number.isFinite(numericPrice) ||
        numericPrice <= 0
    ) {

        return "";

    }


    const language = window.ROMANO_I18N?.language || "fa";
    const locale = language === "en" ? "en-US" : language === "tr" ? "tr-TR" : language === "ar" ? "ar" : "fa-IR";
    const currencyLabel = window.ROMANO_I18N?.ui?.("currency") || " تومان";
    return new Intl.NumberFormat(locale).format(numericPrice) + currencyLabel;

}


/* =========================================================
   22. SECURITY HELPERS
========================================================= */

/**
 * Escape text before inserting into HTML.
 *
 * @param {*} value
 * @returns {string}
 */

function escapeHTML(value) {

    return String(value ?? "")
        .replaceAll(
            "&",
            "&amp;"
        )
        .replaceAll(
            "<",
            "&lt;"
        )
        .replaceAll(
            ">",
            "&gt;"
        )
        .replaceAll(
            '"',
            "&quot;"
        )
        .replaceAll(
            "'",
            "&#039;"
        );

}


/**
 * Escape attribute values.
 *
 * @param {*} value
 * @returns {string}
 */

function escapeAttribute(value) {

    return escapeHTML(
        value
    );

}


/* =========================================================
   23. CROSS-TAB DATA SYNC
========================================================= */

/*
 * If the Admin Panel is open in another browser tab/window
 * under the same origin, the customer menu can detect
 * localStorage changes automatically.
 *
 * This does NOT turn localStorage into a backend.
 * It simply improves the single-browser/same-origin MVP.
 */

window.addEventListener(
    "storage",
    event => {

        if (
            !Object.values(
                ROMANO_STORAGE_KEYS
            ).includes(event.key)
        ) {

            return;

        }


        refreshApplicationData();


        renderRestaurantInformation();

        renderCategories();

        renderFeaturedProducts();

        renderMenuCategories();

        renderNavigation();

        enhanceHorizontalScrollers();

        initializeCategoryObserver();
        initializePrimaryNavigationObserver();
        window.dispatchEvent(new CustomEvent("romano:data-updated"));

    }
);


/* =========================================================
   END OF APPLICATION
========================================================= */

/* =========================================================
   Rv4.3 — CUSTOMER EXPERIENCE LAYER (MERGED)
   
========================================================= */
/* =========================================================
   ROMANO Rv4.3 / UX+
   Progressive enhancements. Keeps the existing MVP logic intact.
========================================================= */
"use strict";

(() => {
    const ready = fn => {
        if (document.readyState === "loading") {
            document.addEventListener("DOMContentLoaded", fn, { once: true });
        } else {
            fn();
        }
    };

    ready(() => {
        initSkipLink();
        initHeaderEffects();
        initReadingProgress();
        initMenuSearch();
        initCategoryRail();
        initBackToTop();
        initModalEnhancements();
        initDeepLinkProduct();
    });

    function initSkipLink() {
        if (document.querySelector(".rv4-skip-link")) return;
        const link = document.createElement("a");
        link.className = "rv4-skip-link";
        link.href = "#menu";
        link.textContent = window.ROMANO_I18N?.ui?.("skipToMenu") || "رفتن به منو";
        document.body.prepend(link);
    }

    function initHeaderEffects() {
        const header = document.querySelector(".site-header");
        if (!header) return;
        const update = () => header.classList.toggle("is-scrolled", window.scrollY > 18);
        update();
        window.addEventListener("scroll", update, { passive: true });
    }

    function initReadingProgress() {
        const bar = document.createElement("div");
        bar.className = "rv4-top-progress";
        bar.setAttribute("aria-hidden", "true");
        document.body.appendChild(bar);

        const update = () => {
            const doc = document.documentElement;
            const max = doc.scrollHeight - window.innerHeight;
            const progress = max > 0 ? Math.min(1, Math.max(0, window.scrollY / max)) : 0;
            bar.style.transform = `scaleX(${progress})`;
        };
        update();
        window.addEventListener("scroll", update, { passive: true });
        window.addEventListener("resize", update, { passive: true });
    }

    function getProducts() {
        return Array.isArray(window.menuProducts) ? window.menuProducts : (typeof menuProducts !== "undefined" ? menuProducts : []);
    }

    function getCategories() {
        const categories = Array.isArray(window.menuCategories) ? window.menuCategories : (typeof menuCategories !== "undefined" ? menuCategories : []);
        return categories.map(category => window.ROMANO_I18N?.localizeCategory(category) || category);
    }

    function initMenuSearch() {
        const menu = document.querySelector("#menu");
        if (!menu || document.querySelector(".rv4-menu-toolbar")) return;

        const toolbar = document.createElement("div");
        toolbar.className = "rv4-menu-toolbar";
        toolbar.innerHTML = `
            <div class="rv4-search-shell">
                <span class="rv4-search-icon" aria-hidden="true">⌕</span>
                <label class="sr-only" for="rv4-menu-search">${window.ROMANO_I18N?.ui?.("searchSr") || "جستجوی منو"}</label>
                <input id="rv4-menu-search" type="search" placeholder="${window.ROMANO_I18N?.ui?.("search") || "جستجو در منوی رمانو…"}" autocomplete="off">
            </div>
            <span class="rv4-toolbar-hint" aria-hidden="true">/</span>
        `;

        const rail = document.createElement("div");
        rail.className = "rv4-category-rail";
        rail.id = "rv4-category-rail";
        rail.setAttribute("aria-label", window.ROMANO_I18N?.ui?.("categories") || "دسته‌بندی‌های منو");
        rail.innerHTML = `<div class="rv4-category-rail-inner"></div>`;

        menu.prepend(rail);
        menu.prepend(toolbar);

        const backdrop = document.createElement("div");
        backdrop.className = "rv4-search-backdrop";
        backdrop.setAttribute("aria-hidden", "true");
        document.body.appendChild(backdrop);

        const results = document.createElement("div");
        results.className = "rv4-search-results";
        results.setAttribute("role", "dialog");
        results.setAttribute("aria-label", window.ROMANO_I18N?.ui?.("results") || "نتایج جستجوی منو");
        results.innerHTML = `<div class="rv4-search-results__inner"></div>`;
        document.body.appendChild(results);

        const input = toolbar.querySelector("input");
        const resultsInner = results.firstElementChild;
        let lastQuery = "";

        const closeResults = () => {
            results.classList.remove("is-open");
            backdrop.classList.remove("is-open");
            input.removeAttribute("aria-expanded");
        };

        const openResults = () => {
            results.classList.add("is-open");
            backdrop.classList.add("is-open");
            input.setAttribute("aria-expanded", "true");
        };

        const renderResults = query => {
            const q = query.trim().toLocaleLowerCase("fa");
            lastQuery = q;
            if (!q) {
                closeResults();
                return;
            }
            const products = getProducts().filter(p => p && p.active !== false);
            const matches = products.filter(product => {
                const localized = window.ROMANO_I18N?.localizeProduct(product) || product;
                const haystack = [localized.name, localized.description, localized.categoryName].join(" ").toLocaleLowerCase();
                return haystack.includes(q);
            }).slice(0, 12);

            resultsInner.innerHTML = matches.length ? matches.map(product => {
                product = window.ROMANO_I18N?.localizeProduct(product) || product;
                return `
                <button class="rv4-result" type="button" data-product-id="${escapeAttribute(product.id)}">
                    <img src="${escapeAttribute(product.image || "")}" alt="" loading="lazy">
                    <span>
                        <span class="rv4-result__name">${escapeHTML(product.name)}</span>
                        <span class="rv4-result__meta">${escapeHTML(product.categoryName || "")}</span>
                    </span>
                    <span class="rv4-result__price">${formatPrice(product.price)}</span>
                </button>
            `;
            }).join("") : `<div class="rv4-result-empty">${window.ROMANO_I18N?.language === "en" ? `No results found for “${escapeHTML(query)}”.` : window.ROMANO_I18N?.language === "tr" ? `“${escapeHTML(query)}” için sonuç bulunamadı.` : window.ROMANO_I18N?.language === "ar" ? `لم يتم العثور على نتائج لـ «${escapeHTML(query)}».` : `نتیجه‌ای برای «${escapeHTML(query)}» پیدا نشد.`}</div>`;
            openResults();
        };

        input.addEventListener("input", e => renderResults(e.target.value));
        input.addEventListener("focus", () => { if (lastQuery) openResults(); });
        results.addEventListener("click", e => {
            const button = e.target.closest("[data-product-id]");
            if (!button) return;
            const id = button.dataset.productId;
            closeResults();
            input.value = "";
            if (typeof window.openProductModal === "function") window.openProductModal(id);
            else if (typeof openProductModal === "function") openProductModal(id);
        });
        backdrop.addEventListener("click", closeResults);

        document.addEventListener("keydown", e => {
            const target = e.target;
            const typing = target && ["INPUT","TEXTAREA","SELECT"].includes(target.tagName);
            if (e.key === "/" && !typing && !e.metaKey && !e.ctrlKey && !e.altKey) {
                e.preventDefault();
                input.focus();
            }
            if (e.key === "Escape") closeResults();
        });

        const navRail = rail.querySelector(".rv4-category-rail-inner");
        const cats = getCategories();
        const counts = getProducts().reduce((acc, p) => {
            if (p.active !== false) acc[p.category] = (acc[p.category] || 0) + 1;
            return acc;
        }, {});
        navRail.innerHTML = cats.filter(c => counts[c.id]).map(c => `
            <a href="#category-${escapeAttribute(c.id)}" data-rail-id="${escapeAttribute(c.id)}">
                ${escapeHTML(c.name)} <span class="count">${counts[c.id]}</span>
            </a>
        `).join("");

        let observer = "IntersectionObserver" in window ? new IntersectionObserver(entries => {
            entries.forEach(entry => {
                if (!entry.isIntersecting) return;
                const id = entry.target.id.replace(/^category-/, "");
                navRail.querySelectorAll("a").forEach(a => a.classList.toggle("is-active", a.dataset.railId === id));
            });
        }, { rootMargin: "-35% 0px -55% 0px", threshold: 0.01 }) : null;
        const observeSections = () => {
            if (!observer) return;
            document.querySelectorAll(".menu-category").forEach(section => observer.observe(section));
        };
        observeSections();
        if (!document.querySelector(".menu-category")) {
            let attempts = 0;
            const retry = () => {
                attempts += 1;
                if (document.querySelector(".menu-category")) observeSections();
                else if (attempts < 20) setTimeout(retry, 50);
            };
            retry();
        }

        window.addEventListener("romano:data-updated", () => {
            const counts = getProducts().reduce((acc, product) => {
                if (product?.active !== false) acc[product.category] = (acc[product.category] || 0) + 1;
                return acc;
            }, {});
            navRail.innerHTML = getCategories()
                .filter(category => counts[category.id])
                .map(category => `<a href="#category-${escapeAttribute(category.id)}" data-rail-id="${escapeAttribute(category.id)}">${escapeHTML(category.name)} <span class="count">${counts[category.id]}</span></a>`)
                .join("");
            observer?.disconnect();
            observeSections();
            if (lastQuery) renderResults(lastQuery);
        });

        document.addEventListener("romano:language-changed", () => {
            input.placeholder = window.ROMANO_I18N?.ui?.("search") || "جستجو در منوی رمانو…";
            toolbar.querySelector("label")?.replaceChildren(document.createTextNode(window.ROMANO_I18N?.ui?.("searchSr") || "جستجوی منو"));
            rail.setAttribute("aria-label", window.ROMANO_I18N?.ui?.("categories") || "دسته‌بندی‌های منو");
            results.setAttribute("aria-label", window.ROMANO_I18N?.ui?.("results") || "نتایج جستجوی منو");
            navRail.innerHTML = getCategories()
                .filter(category => getProducts().some(product => product?.active !== false && product.category === category.id))
                .map(category => `<a href="#category-${escapeAttribute(category.id)}" data-rail-id="${escapeAttribute(category.id)}">${escapeHTML(category.name)} <span class="count">${getProducts().filter(product => product?.active !== false && product.category === category.id).length}</span></a>`)
                .join("");
            if (lastQuery) renderResults(lastQuery);
        });
    }

    function initCategoryRail() {
        const rail = document.querySelector("#rv4-category-rail");
        if (!rail) return;
        rail.addEventListener("click", () => setTimeout(() => {
            if (typeof window.closeNavigation === "function") window.closeNavigation();
        }, 0));
    }

    function initBackToTop() {
        const button = document.createElement("button");
        button.className = "rv4-back-top";
        button.type = "button";
        button.setAttribute("aria-label", window.ROMANO_I18N?.ui?.("backToTop") || "بازگشت به بالای صفحه");
        button.innerHTML = "↑";
        document.body.appendChild(button);
        const update = () => button.classList.toggle("is-visible", window.scrollY > window.innerHeight * 0.7);
        update();
        window.addEventListener("scroll", update, { passive: true });
        button.addEventListener("click", () => window.scrollTo({ top: 0, behavior: "smooth" }));
    }


    function initDeepLinkProduct() {
        const openFromHash = () => {
            let hash = location.hash || "";
            try { hash = decodeURIComponent(hash); } catch (_) { return; }

            if (!hash.startsWith("#product-")) {
                if (document.querySelector(".product-modal.is-open")) window.closeProductModal?.();
                return;
            }

            const id = hash.slice("#product-".length);
            let attempts = 0;
            const tryOpen = () => {
                attempts += 1;
                const exists = getProducts().some(p => String(p?.id) === String(id) && p.active !== false);
                if (exists && typeof window.openProductModal === "function") {
                    window.openProductModal(id);
                    return;
                }
                if (attempts < 40) window.setTimeout(tryOpen, 50);
            };
            tryOpen();
        };

        window.addEventListener("hashchange", openFromHash);
        openFromHash();
    }

    function initModalEnhancements() {
        const modal = document.querySelector(".product-modal");
        const content = modal?.querySelector(".modal-content");
        if (!modal || !content || document.querySelector(".rv4-modal-actions")) return;
        const actions = document.createElement("div");
        actions.className = "rv4-modal-actions";
        actions.innerHTML = `
            <button class="rv4-modal-action" type="button" data-rv4-share></button>
            <button class="rv4-modal-action" type="button" data-rv4-copy></button>
        `;
        content.appendChild(actions);

        // Labels are written from the current language, and rewritten whenever it changes
        // (the buttons are created once, so they must not capture the language at creation time).
        const labelShare = actions.querySelector("[data-rv4-share]");
        const labelCopy = actions.querySelector("[data-rv4-copy]");
        const applyActionLabels = () => {
            labelShare.textContent = window.ROMANO_I18N?.ui?.("share") || "اشتراک‌گذاری";
            labelCopy.textContent = window.ROMANO_I18N?.ui?.("copyLink") || "کپی لینک";
        };
        applyActionLabels();
        document.addEventListener("romano:language-changed", applyActionLabels);
        const getActiveProduct = () => {
            const product = window.RomanoActiveProduct;
            return product && product.id ? product : null;
        };
        const productUrl = product => `${location.origin}${location.pathname}#product-${encodeURIComponent(product.id)}`;

        // The core modal is the single source of truth. Do not cache the
        // selected product here: direct card clicks can bypass this wrapper.
        const originalOpen = window.openProductModal || (typeof openProductModal === "function" ? openProductModal : null);
        if (originalOpen && !window.__romanoRv4OpenWrapped) {
            window.openProductModal = id => originalOpen(id);
            window.__romanoRv4OpenWrapped = true;
        }

        actions.querySelector("[data-rv4-share]").addEventListener("click", async () => {
            const product = getActiveProduct();
            if (!product) return;
            const shareData = { title: `ROMANO | ${product.name}`, text: product.description || product.name, url: productUrl(product) };
            try {
                if (typeof navigator.share === "function") await navigator.share(shareData);
                else await copyText(shareData.url);
            } catch (_) {}
        });
        actions.querySelector("[data-rv4-copy]").addEventListener("click", async () => {
            const product = getActiveProduct();
            if (!product) return;
            const button = actions.querySelector("[data-rv4-copy]");
            if (!(await copyText(productUrl(product)))) return;
            button.textContent = window.ROMANO_I18N?.ui?.("copied") || "کپی شد ✓";
            setTimeout(applyActionLabels, 1400);
        });

        async function copyText(text) {
            try {
                if (navigator.clipboard?.writeText) {
                    await navigator.clipboard.writeText(text);
                    return true;
                }
                const helper = document.createElement("textarea");
                helper.value = text;
                helper.setAttribute("readonly", "");
                helper.style.position = "fixed";
                helper.style.opacity = "0";
                document.body.appendChild(helper);
                helper.select();
                const ok = document.execCommand("copy");
                helper.remove();
                return ok;
            } catch (_) { return false; }
        }

        // Keep the URL and modal state in sync for shareable product links.
        const observer = new MutationObserver(() => {
            if (modal.classList.contains("is-open")) {
                const product = getActiveProduct();
                if (product?.id) history.replaceState(null, "", `#product-${encodeURIComponent(product.id)}`);
            }
        });
        observer.observe(modal, { attributes: true, attributeFilter: ["class"] });
        modal.addEventListener("click", event => {
            if (event.target.closest("[data-modal-close]")) {
                if (location.hash.startsWith("#product-")) history.replaceState(null, "", `${location.pathname}${location.search}`);
            }
        });
    }

})();

/* =========================================================
   ROMANO Rv4.3 — EDITORIAL CONTENT LAYER
========================================================= */
(function () {
    "use strict";

    function getProducts() {
        if (Array.isArray(window.menuProducts)) return window.menuProducts;
        return typeof menuProducts !== "undefined" && Array.isArray(menuProducts) ? menuProducts : [];
    }

    function getFeatured() {
        return getProducts().filter(p => p && p.active !== false && p.featured === true);
    }

    function renderSignatureDish() {
        const host = document.querySelector("#signature-dish");
        if (!host) return;
        const product = window.ROMANO_I18N?.localizeProduct(getFeatured()[0]) || getFeatured()[0];
        if (!product) {
            host.hidden = true;
            return;
        }

        host.hidden = false;
        host.innerHTML = `
            <div class="romano-signature-dish__media">
                ${product.image ? `<img src="${escapeAttribute(product.image)}" alt="${escapeAttribute(product.name)}" loading="lazy">` : `<div class="image-fallback" aria-hidden="true">ROMANO</div>`}
            </div>
            <div class="romano-signature-dish__copy">
                <span class="romano-signature-dish__eyebrow">${escapeHTML(window.ROMANO_I18N?.ui?.("signatureEyebrow", product.categoryName || "ROMANO") || `SIGNATURE DISH · ${product.categoryName || "ROMANO"}`)}</span>
                <h3 class="romano-signature-dish__title">${escapeHTML(product.name)}</h3>
                <p class="romano-signature-dish__desc">${escapeHTML(product.description || (window.ROMANO_I18N?.ui?.("signatureFallback") || "انتخاب ویژه‌ی امروز رمانو."))}</p>
                <div class="romano-signature-dish__footer">
                    <span class="romano-signature-dish__price">${escapeHTML(formatPrice(product.price))}</span>
                    <button class="romano-signature-dish__button" type="button" data-signature-product="${escapeHTML(product.id)}">${window.ROMANO_I18N?.ui?.("signatureButton") || "مشاهده جزئیات"}</button>
                </div>
            </div>
        `;

        const button = host.querySelector("[data-signature-product]");
        button?.addEventListener("click", () => {
            if (typeof window.openProductModal === "function") window.openProductModal(product.id);
        });
    }

    window.renderSignatureDish = renderSignatureDish;

    function initSignatureDish() {
        renderSignatureDish();
        window.setTimeout(renderSignatureDish, 80);
        window.setTimeout(renderSignatureDish, 300);
    }

    if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", initSignatureDish, { once: true });
    } else {
        initSignatureDish();
    }

    /* Keep signature card in sync after the admin panel changes localStorage. */
    if ("serviceWorker" in navigator && window.location.protocol !== "file:") {
        navigator.serviceWorker.register("./sw.js", { scope: "./" }).catch(error => {
            console.warn("ROMANO service worker registration skipped:", error);
        });
    }

    window.addEventListener("storage", event => {
        if (["romano_products", "romano_categories"].includes(event.key)) {
            window.setTimeout(renderSignatureDish, 40);
        }
    });
})();


